export const carBrands = [
  { label: "Acura", value: "Acura" },
  { label: "Alfa Romeo", value: "Alfa Romeo" },
  { label: "Aston Martin", value: "Aston Martin" },
  { label: "Audi", value: "Audi" },
  { label: "Bentley", value: "Bentley" },
  { label: "BMW", value: "BMW" },
  { label: "Bugatti", value: "Bugatti" },
  { label: "Buick", value: "Buick" },
  { label: "Cadillac", value: "Cadillac" },
  { label: "Changan", value: "Changan" },
  { label: "Chevrolet", value: "Chevrolet" },
  { label: "Chrysler", value: "Chrysler" },
  { label: "Citroën", value: "Citroën" },
  { label: "Dacia", value: "Dacia" },
  { label: "Daihatsu", value: "Daihatsu" },
  { label: "Dodge", value: "Dodge" },
  { label: "Ferrari", value: "Ferrari" },
  { label: "Fiat", value: "Fiat" },
  { label: "Ford", value: "Ford" },
  { label: "Genesis", value: "Genesis" },
  { label: "GMC", value: "GMC" },
  { label: "Haval", value: "Haval" },
  { label: "Honda", value: "Honda" },
  { label: "Hummer", value: "Hummer" },
  { label: "Hyundai", value: "Hyundai" },
  { label: "Infiniti", value: "Infiniti" },
  { label: "Jaguar", value: "Jaguar" },
  { label: "Jeep", value: "Jeep" },
  { label: "Kia", value: "Kia" },
  { label: "Lamborghini", value: "Lamborghini" },
  { label: "Land Rover", value: "Land Rover" },
  { label: "Lexus", value: "Lexus" },
  { label: "Lincoln", value: "Lincoln" },
  { label: "Maserati", value: "Maserati" },
  { label: "Mazda", value: "Mazda" },
  { label: "McLaren", value: "McLaren" },
  { label: "Mercedes", value: "Mercedes" },
  { label: "Mini", value: "Mini" },
  { label: "Mitsubishi", value: "Mitsubishi" },
  { label: "Neta", value: "Neta" },
  { label: "Nissan", value: "Nissan" },
  { label: "Pagani", value: "Pagani" },
  { label: "Peugeot", value: "Peugeot" },
  { label: "Pontiac", value: "Pontiac" },
  { label: "Porsche", value: "Porsche" },
  { label: "Range Rover", value: "Range Rover" },
  { label: "Ram", value: "Ram" },
  { label: "Renault", value: "Renault" },
  { label: "Rolls-Royce", value: "Rolls-Royce" },
  { label: "Saab", value: "Saab" },
  { label: "Saturn", value: "Saturn" },
  { label: "Scion", value: "Scion" },
  { label: "Smart", value: "Smart" },
  { label: "Spyker", value: "Spyker" },
  { label: "Subaru", value: "Subaru" },
  { label: "Suzuki", value: "Suzuki" },
  { label: "Tesla", value: "Tesla" },
  { label: "Toyota", value: "Toyota" },
  { label: "Volkswagen", value: "Volkswagen" },
  { label: "Volvo", value: "Volvo" },
];

export type CarBrand =
  | ""
  | "Acura"
  | "Alfa Romeo"
  | "Aston Martin"
  | "Audi"
  | "Bentley"
  | "BMW"
  | "Bugatti"
  | "Buick"
  | "Cadillac"
  | "Changan"
  | "Chevrolet"
  | "Chrysler"
  | "Citroën"
  | "Dacia"
  | "Daihatsu"
  | "Dodge"
  | "Ferrari"
  | "Fiat"
  | "Ford"
  | "Genesis"
  | "GMC"
  | "Haval"
  | "Honda"
  | "Hummer"
  | "Hyundai"
  | "Infiniti"
  | "Jaguar"
  | "Jeep"
  | "Kia"
  | "Lamborghini"
  | "Land Rover"
  | "Lexus"
  | "Lincoln"
  | "Maserati"
  | "Mazda"
  | "McLaren"
  | "Mercedes"
  | "Mini"
  | "Mitsubishi"
  | "Neta"
  | "Nissan"
  | "Pagani"
  | "Peugeot"
  | "Pontiac"
  | "Porsche"
  | "Range Rover"
  | "Ram"
  | "Renault"
  | "Rolls-Royce"
  | "Saab"
  | "Saturn"
  | "Scion"
  | "Smart"
  | "Spyker"
  | "Subaru"
  | "Suzuki"
  | "Tesla"
  | "Toyota"
  | "Volkswagen"
  | "Volvo";

export const getBrandFromModel = (model: string): CarBrand | null => {
  for (const [brand, models] of Object.entries(CarModel)) {
    if (models.some((m) => m.label === model || m.value === model)) {
      return brand as CarBrand; // Cast the brand as CarBrand
    }
  }

  return null; // Return null if no matching brand is found
};

export const CarModel: Record<string | CarBrand, { label: string; value: string }[]> = {
  "": [],
  Acura: [
    { label: "Acura CL", value: "Acura CL" },
    { label: "Acura ILX", value: "Acura ILX" },
    { label: "Acura MDX", value: "Acura MDX" },
    { label: "Acura NSX", value: "Acura NSX" },
    { label: "Acura RDX", value: "Acura RDX" },
    { label: "Acura RL", value: "Acura RL" },
    { label: "Acura RLX", value: "Acura RLX" },
    { label: "Acura RSX", value: "Acura RSX" },
    { label: "Acura TL", value: "Acura TL" },
    { label: "Acura TLX", value: "Acura TLX" },
    { label: "Acura TSX", value: "Acura TSX" },
    { label: "Acura ZDX", value: "Acura ZDX" },
  ],

  "Alfa Romeo": [
    { label: "Alfa Romeo 4C", value: "Alfa Romeo 4C" },
    { label: "Alfa Romeo 8C Competizione", value: "Alfa Romeo 8C Competizione" },
    { label: "Alfa Romeo Giulia", value: "Alfa Romeo Giulia" },
    { label: "Alfa Romeo Giulietta", value: "Alfa Romeo Giulietta" },
    { label: "Alfa Romeo Stelvio", value: "Alfa Romeo Stelvio" },
  ],

  "Aston Martin": [
    { label: "Aston Martin DB11", value: "Aston Martin DB11" },
    { label: "Aston Martin DB9", value: "Aston Martin DB9" },
    { label: "Aston Martin DBS", value: "Aston Martin DBS" },
    { label: "Aston Martin Rapide", value: "Aston Martin Rapide" },
    { label: "Aston Martin Vanquish", value: "Aston Martin Vanquish" },
    { label: "Aston Martin Vantage", value: "Aston Martin Vantage" },
  ],

  Audi: [
    { label: "Audi A1", value: "Audi A1" },
    { label: "Audi A3", value: "Audi A3" },
    { label: "Audi A3 Sportback", value: "Audi A3 Sportback" },
    { label: "Audi A4", value: "Audi A4" },
    { label: "Audi A4 Avant", value: "Audi A4 Avant" },
    { label: "Audi A5", value: "Audi A5" },
    { label: "Audi A5 Coupe", value: "Audi A5 Coupe" },
    { label: "Audi A5 Sportback", value: "Audi A5 Sportback" },
    { label: "Audi A6", value: "Audi A6" },
    { label: "Audi A6 Avant", value: "Audi A6 Avant" },
    { label: "Audi A7", value: "Audi A7" },
    { label: "Audi A7 Sportback", value: "Audi A7 Sportback" },
    { label: "Audi A8", value: "Audi A8" },
    { label: "Audi A8 L", value: "Audi A8 L" },
    { label: "Audi Q2", value: "Audi Q2" },
    { label: "Audi Q3", value: "Audi Q3" },
    { label: "Audi Q3 Sportback", value: "Audi Q3 Sportback" },
    { label: "Audi Q4 e-tron", value: "Audi Q4 e-tron" },
    { label: "Audi Q5", value: "Audi Q5" },
    { label: "Audi Q5 Sportback", value: "Audi Q5 Sportback" },
    { label: "Audi Q7", value: "Audi Q7" },
    { label: "Audi Q8", value: "Audi Q8" },
    { label: "Audi Q8 e-tron", value: "Audi Q8 e-tron" },
    { label: "Audi TT", value: "Audi TT" },
    { label: "Audi TT Coupe", value: "Audi TT Coupe" },
    { label: "Audi TT Roadster", value: "Audi TT Roadster" },
    { label: "Audi R8", value: "Audi R8" },
    { label: "Audi S1", value: "Audi S1" },
    { label: "Audi S3", value: "Audi S3" },
    { label: "Audi S4", value: "Audi S4" },
    { label: "Audi S5", value: "Audi S5" },
    { label: "Audi S6", value: "Audi S6" },
    { label: "Audi S7", value: "Audi S7" },
    { label: "Audi S8", value: "Audi S8" },
    { label: "Audi SQ2", value: "Audi SQ2" },
    { label: "Audi SQ5", value: "Audi SQ5" },
    { label: "Audi SQ7", value: "Audi SQ7" },
    { label: "Audi SQ8", value: "Audi SQ8" },
    { label: "Audi RS3", value: "Audi RS3" },
    { label: "Audi RS4 Avant", value: "Audi RS4 Avant" },
    { label: "Audi RS5", value: "Audi RS5" },
    { label: "Audi RS6 Avant", value: "Audi RS6 Avant" },
    { label: "Audi RS7", value: "Audi RS7" },
    { label: "Audi RS Q3", value: "Audi RS Q3" },
    { label: "Audi RS Q5", value: "Audi RS Q5" },
    { label: "Audi RS Q7", value: "Audi RS Q7" },
    { label: "Audi RS Q8", value: "Audi RS Q8" },
    { label: "Audi Q7 e-tron", value: "Audi Q7 e-tron" },
    { label: "Audi A3 e-tron", value: "Audi A3 e-tron" },
    { label: "Audi A4 e-tron", value: "Audi A4 e-tron" },
    { label: "Audi A6 e-tron", value: "Audi A6 e-tron" },
    { label: "Audi Q4 50 e-tron", value: "Audi Q4 50 e-tron" },
    { label: "Audi Q5 e-tron", value: "Audi Q5 e-tron" },
  ],

  Bentley: [
    { label: "Bentley Bentayga", value: "Bentley Bentayga" },
    { label: "Bentley Continental GT", value: "Bentley Continental GT" },
    { label: "Bentley Flying Spur", value: "Bentley Flying Spur" },
    { label: "Bentley Mulsanne", value: "Bentley Mulsanne" },
  ],

  BMW: [
    { label: "BMW 1 Series", value: "BMW 1 Series" },
    { label: "BMW 2 Series", value: "BMW 2 Series" },
    { label: "BMW 2 Series Coupe", value: "BMW 2 Series Coupe" },
    { label: "BMW 2 Series Gran Coupe", value: "BMW 2 Series Gran Coupe" },
    { label: "BMW 3 Series", value: "BMW 3 Series" },
    { label: "BMW 3 Series Sedan", value: "BMW 3 Series Sedan" },
    { label: "BMW 3 Series Touring", value: "BMW 3 Series Touring" },
    { label: "BMW 4 Series", value: "BMW 4 Series" },
    { label: "BMW 4 Series Coupe", value: "BMW 4 Series Coupe" },
    { label: "BMW 4 Series Gran Coupe", value: "BMW 4 Series Gran Coupe" },
    { label: "BMW 4 Series Convertible", value: "BMW 4 Series Convertible" },
    { label: "BMW 5 Series", value: "BMW 5 Series" },
    { label: "BMW 5 Series Sedan", value: "BMW 5 Series Sedan" },
    { label: "BMW 5 Series Touring", value: "BMW 5 Series Touring" },
    { label: "BMW 6 Series", value: "BMW 6 Series" },
    { label: "BMW 6 Series Coupe", value: "BMW 6 Series Coupe" },
    { label: "BMW 6 Series Gran Coupe", value: "BMW 6 Series Gran Coupe" },
    { label: "BMW 6 Series Convertible", value: "BMW 6 Series Convertible" },
    { label: "BMW 7 Series", value: "BMW 7 Series" },
    { label: "BMW 8 Series", value: "BMW 8 Series" },
    { label: "BMW 8 Series Coupe", value: "BMW 8 Series Coupe" },
    { label: "BMW 8 Series Gran Coupe", value: "BMW 8 Series Gran Coupe" },
    { label: "BMW 8 Series Convertible", value: "BMW 8 Series Convertible" },
    { label: "BMW X1", value: "BMW X1" },
    { label: "BMW X2", value: "BMW X2" },
    { label: "BMW X3", value: "BMW X3" },
    { label: "BMW X4", value: "BMW X4" },
    { label: "BMW X5", value: "BMW X5" },
    { label: "BMW X6", value: "BMW X6" },
    { label: "BMW X7", value: "BMW X7" },
    { label: "BMW Z4", value: "BMW Z4" },
    { label: "BMW i3", value: "BMW i3" },
    { label: "BMW i4", value: "BMW i4" },
    { label: "BMW iX", value: "BMW iX" },
    { label: "BMW iX3", value: "BMW iX3" },
    { label: "BMW M2", value: "BMW M2" },
    { label: "BMW M3", value: "BMW M3" },
    { label: "BMW M4", value: "BMW M4" },
    { label: "BMW M5", value: "BMW M5" },
    { label: "BMW M6", value: "BMW M6" },
    { label: "BMW M8", value: "BMW M8" },
    { label: "BMW X3 M", value: "BMW X3 M" },
    { label: "BMW X4 M", value: "BMW X4 M" },
    { label: "BMW X5 M", value: "BMW X5 M" },
    { label: "BMW X6 M", value: "BMW X6 M" },
    { label: "BMW X7 M", value: "BMW X7 M" },
    { label: "BMW i8", value: "BMW i8" },
    { label: "BMW Z3", value: "BMW Z3" },
    { label: "BMW Z8", value: "BMW Z8" },
  ],

  Bugatti: [
    { label: "Bugatti Chiron", value: "Bugatti Chiron" },
    { label: "Bugatti Veyron", value: "Bugatti Veyron" },
    { label: "Bugatti Divo", value: "Bugatti Divo" },
  ],

  Buick: [
    { label: "Buick Enclave", value: "Buick Enclave" },
    { label: "Buick Encore", value: "Buick Encore" },
    { label: "Buick Envision", value: "Buick Envision" },
    { label: "Buick LaCrosse", value: "Buick LaCrosse" },
    { label: "Buick Regal", value: "Buick Regal" },
    { label: "Buick Verano", value: "Buick Verano" },
  ],

  Cadillac: [
    { label: "Cadillac ATS", value: "Cadillac ATS" },
    { label: "Cadillac CT4", value: "Cadillac CT4" },
    { label: "Cadillac CT5", value: "Cadillac CT5" },
    { label: "Cadillac CT6", value: "Cadillac CT6" },
    { label: "Cadillac CTS", value: "Cadillac CTS" },
    { label: "Cadillac Escalade", value: "Cadillac Escalade" },
    { label: "Cadillac SRX", value: "Cadillac SRX" },
    { label: "Cadillac XT4", value: "Cadillac XT4" },
    { label: "Cadillac XT5", value: "Cadillac XT5" },
    { label: "Cadillac XT6", value: "Cadillac XT6" },
    { label: "Cadillac XTS", value: "Cadillac XTS" },
  ],

  Changan: [
    { label: "Changan CS35", value: "Changan CS35" },
    { label: "Changan CS55", value: "Changan CS55" },
    { label: "Changan CS75", value: "Changan CS75" },
    { label: "Changan CS85", value: "Changan CS85" },
    { label: "Changan CS95", value: "Changan CS95" },
    { label: "Changan Eado", value: "Changan Eado" },
    { label: "Changan Eado XT", value: "Changan Eado XT" },
    { label: "Changan Eado RS", value: "Changan Eado RS" },
    { label: "Changan Alsvin", value: "Changan Alsvin" },
    { label: "Changan V7", value: "Changan V7" },
    { label: "Changan V5", value: "Changan V5" },
    { label: "Changan Star 7", value: "Changan Star 7" },
    { label: "Changan Kaicheng", value: "Changan Kaicheng" },
    { label: "Changan Auchan", value: "Changan Auchan" },
    { label: "Changan UNI-T", value: "Changan UNI-T" },
    { label: "Changan UNI-K", value: "Changan UNI-K" },
    { label: "Changan UNI-V", value: "Changan UNI-V" },
  ],

  Chevrolet: [
    { label: "Chevrolet Avalanche", value: "Chevrolet Avalanche" },
    { label: "Chevrolet Aveo", value: "Chevrolet Aveo" },
    { label: "Chevrolet Blazer", value: "Chevrolet Blazer" },
    { label: "Chevrolet Bolt", value: "Chevrolet Bolt" },
    { label: "Chevrolet Camaro", value: "Chevrolet Camaro" },
    { label: "Chevrolet Captiva", value: "Chevrolet Captiva" },
    { label: "Chevrolet Cobalt", value: "Chevrolet Cobalt" },
    { label: "Chevrolet Colorado", value: "Chevrolet Colorado" },
    { label: "Chevrolet Corvette", value: "Chevrolet Corvette" },
    { label: "Chevrolet Cruze", value: "Chevrolet Cruze" },
    { label: "Chevrolet Equinox", value: "Chevrolet Equinox" },
    { label: "Chevrolet Impala", value: "Chevrolet Impala" },
    { label: "Chevrolet Malibu", value: "Chevrolet Malibu" },
    { label: "Chevrolet Silverado", value: "Chevrolet Silverado" },
    { label: "Chevrolet Sonic", value: "Chevrolet Sonic" },
    { label: "Chevrolet Spark", value: "Chevrolet Spark" },
    { label: "Chevrolet Suburban", value: "Chevrolet Suburban" },
    { label: "Chevrolet Tahoe", value: "Chevrolet Tahoe" },
    { label: "Chevrolet Trailblazer", value: "Chevrolet Trailblazer" },
    { label: "Chevrolet Traverse", value: "Chevrolet Traverse" },
    { label: "Chevrolet Trax", value: "Chevrolet Trax" },
    { label: "Chevrolet Volt", value: "Chevrolet Volt" },
  ],

  Chrysler: [
    { label: "Chrysler 200", value: "Chrysler 200" },
    { label: "Chrysler 300", value: "Chrysler 300" },
    { label: "Chrysler Aspen", value: "Chrysler Aspen" },
    { label: "Chrysler Pacifica", value: "Chrysler Pacifica" },
    { label: "Chrysler PT Cruiser", value: "Chrysler PT Cruiser" },
    { label: "Chrysler Sebring", value: "Chrysler Sebring" },
    { label: "Chrysler Town & Country", value: "Chrysler Town & Country" },
  ],

  Citroën: [
    { label: "Citroën Berlingo", value: "Citroën Berlingo" },
    { label: "Citroën C1", value: "Citroën C1" },
    { label: "Citroën C3", value: "Citroën C3" },
    { label: "Citroën C4", value: "Citroën C4" },
    { label: "Citroën C5", value: "Citroën C5" },
    { label: "Citroën C6", value: "Citroën C6" },
    { label: "Citroën C8", value: "Citroën C8" },
    { label: "Citroën DS3", value: "Citroën DS3" },
    { label: "Citroën DS4", value: "Citroën DS4" },
    { label: "Citroën DS5", value: "Citroën DS5" },
    { label: "Citroën Evasion", value: "Citroën Evasion" },
    { label: "Citroën Nemo", value: "Citroën Nemo" },
    { label: "Citroën Xsara", value: "Citroën Xsara" },
  ],

  Dacia: [
    { label: "Dacia Logan", value: "Dacia Logan" },
    { label: "Dacia Logan MCV", value: "Dacia Logan MCV" },
    { label: "Dacia Sandero", value: "Dacia Sandero" },
    { label: "Dacia Sandero Stepway", value: "Dacia Sandero Stepway" },
    { label: "Dacia Duster", value: "Dacia Duster" },
    { label: "Dacia Duster 4x4", value: "Dacia Duster 4x4" },
    { label: "Dacia Dokker", value: "Dacia Dokker" },
    { label: "Dacia Dokker Van", value: "Dacia Dokker Van" },
    { label: "Dacia Lodgy", value: "Dacia Lodgy" },
    { label: "Dacia Spring", value: "Dacia Spring" },
    { label: "Dacia Jogger", value: "Dacia Jogger" },
    { label: "Dacia SUV", value: "Dacia SUV" },
    { label: "Dacia MCV", value: "Dacia MCV" },
  ],

  Daihatsu: [
    { label: "Daihatsu Copen", value: "Daihatsu Copen" },
    { label: "Daihatsu Terios", value: "Daihatsu Terios" },
  ],

  Dodge: [
    { label: "Dodge Avenger", value: "Dodge Avenger" },
    { label: "Dodge Caliber", value: "Dodge Caliber" },
    { label: "Dodge Challenger", value: "Dodge Challenger" },
    { label: "Dodge Charger", value: "Dodge Charger" },
    { label: "Dodge Dakota", value: "Dodge Dakota" },
    { label: "Dodge Dart", value: "Dodge Dart" },
    { label: "Dodge Durango", value: "Dodge Durango" },
    { label: "Dodge Grand Caravan", value: "Dodge Grand Caravan" },
    { label: "Dodge Journey", value: "Dodge Journey" },
    { label: "Dodge Nitro", value: "Dodge Nitro" },
    { label: "Dodge Ram", value: "Dodge Ram" },
    { label: "Dodge Viper", value: "Dodge Viper" },
  ],

  Ferrari: [
    { label: "Ferrari 458 Italia", value: "Ferrari 458 Italia" },
    { label: "Ferrari 488", value: "Ferrari 488" },
    { label: "Ferrari California", value: "Ferrari California" },
    { label: "Ferrari F12", value: "Ferrari F12" },
    { label: "Ferrari F8", value: "Ferrari F8" },
    { label: "Ferrari GTC4Lusso", value: "Ferrari GTC4Lusso" },
    { label: "Ferrari LaFerrari", value: "Ferrari LaFerrari" },
    { label: "Ferrari Portofino", value: "Ferrari Portofino" },
    { label: "Ferrari Roma", value: "Ferrari Roma" },
    { label: "Ferrari SF90", value: "Ferrari SF90" },
    { label: "Fiat 124 Spider", value: "Fiat 124 Spider" },
    { label: "Fiat 500", value: "Fiat 500" },
    { label: "Fiat 500L", value: "Fiat 500L" },
    { label: "Fiat 500X", value: "Fiat 500X" },
    { label: "Fiat Doblo", value: "Fiat Doblo" },
    { label: "Fiat Panda", value: "Fiat Panda" },
    { label: "Fiat Punto", value: "Fiat Punto" },
  ],

  Fiat: [
    { label: "Fiat 124 Spider", value: "Fiat 124 Spider" },
    { label: "Fiat 500", value: "Fiat 500" },
    { label: "Fiat 500L", value: "Fiat 500L" },
    { label: "Fiat 500X", value: "Fiat 500X" },
    { label: "Fiat Doblo", value: "Fiat Doblo" },
    { label: "Fiat Panda", value: "Fiat Panda" },
    { label: "Fiat Punto", value: "Fiat Punto" },
  ],

  Ford: [
    { label: "Ford Fiesta", value: "Ford Fiesta" },
    { label: "Ford Focus", value: "Ford Focus" },
    { label: "Ford Mondeo", value: "Ford Mondeo" },
    { label: "Ford Fusion", value: "Ford Fusion" },
    { label: "Ford Mustang", value: "Ford Mustang" },
    { label: "Ford GT", value: "Ford GT" },
    { label: "Ford EcoSport", value: "Ford EcoSport" },
    { label: "Ford Kuga", value: "Ford Kuga" },
    { label: "Ford Escape", value: "Ford Escape" },
    { label: "Ford Edge", value: "Ford Edge" },
    { label: "Ford Explorer", value: "Ford Explorer" },
    { label: "Ford Expedition", value: "Ford Expedition" },
    { label: "Ford Bronco", value: "Ford Bronco" },
    { label: "Ford F-150", value: "Ford F-150" },
    { label: "Ford F-250", value: "Ford F-250" },
    { label: "Ford F-350", value: "Ford F-350" },
    { label: "Ford Ranger", value: "Ford Ranger" },
    { label: "Ford Transit Connect", value: "Ford Transit Connect" },
    { label: "Ford Transit", value: "Ford Transit" },
    { label: "Ford Transit Custom", value: "Ford Transit Custom" },
    { label: "Ford Tourneo Connect", value: "Ford Tourneo Connect" },
    { label: "Ford Tourneo Custom", value: "Ford Tourneo Custom" },
    { label: "Ford Mustang Mach-E", value: "Ford Mustang Mach-E" },
    { label: "Ford Focus ST", value: "Ford Focus ST" },
    { label: "Ford Focus RS", value: "Ford Focus RS" },
    { label: "Ford C-Max", value: "Ford C-Max" },
    { label: "Ford Grand C-Max", value: "Ford Grand C-Max" },
    { label: "Ford Puma", value: "Ford Puma" },
    { label: "Ford Ka", value: "Ford Ka" },
    { label: "Ford B-Max", value: "Ford B-Max" },
    { label: "Ford Fusion Hybrid", value: "Ford Fusion Hybrid" },
    { label: "Ford Explorer Hybrid", value: "Ford Explorer Hybrid" },
  ],

  Genesis: [
    { label: "Genesis G70", value: "Genesis G70" },
    { label: "Genesis G80", value: "Genesis G80" },
    { label: "Genesis G90", value: "Genesis G90" },
    { label: "Genesis GV70", value: "Genesis GV70" },
    { label: "Genesis GV80", value: "Genesis GV80" },
  ],

  GMC: [
    { label: "GMC Acadia", value: "GMC Acadia" },
    { label: "GMC Canyon", value: "GMC Canyon" },
    { label: "GMC Envoy", value: "GMC Envoy" },
    { label: "GMC Savana", value: "GMC Savana" },
    { label: "GMC Sierra", value: "GMC Sierra" },
    { label: "GMC Terrain", value: "GMC Terrain" },
    { label: "GMC Yukon", value: "GMC Yukon" },
  ],

  Haval: [
    { label: "Haval H1", value: "Haval H1" },
    { label: "Haval H2", value: "Haval H2" },
    { label: "Haval H4", value: "Haval H4" },
    { label: "Haval H6", value: "Haval H6" },
    { label: "Haval H7", value: "Haval H7" },
    { label: "Haval H8", value: "Haval H8" },
    { label: "Haval H9", value: "Haval H9" },
    { label: "Haval F5", value: "Haval F5" },
    { label: "Haval F7", value: "Haval F7" },
    { label: "Haval F7X", value: "Haval F7X" },
    { label: "Haval F8", value: "Haval F8" },
    { label: "Haval Jolion", value: "Haval Jolion" },
    { label: "Haval Dargo", value: "Haval Dargo" },
  ],

  Honda: [
    { label: "Honda Accord", value: "Honda Accord" },
    { label: "Honda Accord Hybrid", value: "Honda Accord Hybrid" },
    { label: "Honda Civic", value: "Honda Civic" },
    { label: "Honda Civic Coupe", value: "Honda Civic Coupe" },
    { label: "Honda Civic Hatchback", value: "Honda Civic Hatchback" },
    { label: "Honda Civic Type R", value: "Honda Civic Type R" },
    { label: "Honda Clarity", value: "Honda Clarity" },
    { label: "Honda Clarity Plug-In Hybrid", value: "Honda Clarity Plug-In Hybrid" },
    { label: "Honda CR-V", value: "Honda CR-V" },
    { label: "Honda CR-V Hybrid", value: "Honda CR-V Hybrid" },
    { label: "Honda Element", value: "Honda Element" },
    { label: "Honda Fit", value: "Honda Fit" },
    { label: "Honda HR-V", value: "Honda HR-V" },
    { label: "Honda HR-V Hybrid", value: "Honda HR-V Hybrid" },
    { label: "Honda Insight", value: "Honda Insight" },
    { label: "Honda Odyssey", value: "Honda Odyssey" },
    { label: "Honda Passport", value: "Honda Passport" },
    { label: "Honda Pilot", value: "Honda Pilot" },
    { label: "Honda Ridgeline", value: "Honda Ridgeline" },
    { label: "Honda S2000", value: "Honda S2000" },
    { label: "Honda NSX", value: "Honda NSX" },
    { label: "Honda Accord Crosstour", value: "Honda Accord Crosstour" },
    { label: "Honda Crosstour", value: "Honda Crosstour" },
    { label: "Honda CR-Z", value: "Honda CR-Z" },
    { label: "Honda Element", value: "Honda Element" },
    { label: "Honda HR-V", value: "Honda HR-V" },
    { label: "Honda Pilot", value: "Honda Pilot" },
    { label: "Honda Ridgeline", value: "Honda Ridgeline" },
    { label: "Honda S660", value: "Honda S660" },
    { label: "Honda WR-V", value: "Honda WR-V" },
  ],

  Hummer: [
    { label: "Hummer H1", value: "Hummer H1" },
    { label: "Hummer H2", value: "Hummer H2" },
    { label: "Hummer H3", value: "Hummer H3" },
  ],

  Hyundai: [
    { label: "Hyundai i10", value: "Hyundai i10" },
    { label: "Hyundai i20", value: "Hyundai i20" },
    { label: "Hyundai i30", value: "Hyundai i30" },
    { label: "Hyundai i30 Fastback", value: "Hyundai i30 Fastback" },
    { label: "Hyundai i40", value: "Hyundai i40" },
    { label: "Hyundai iX20", value: "Hyundai iX20" },
    { label: "Hyundai iX35", value: "Hyundai iX35" },
    { label: "Hyundai Tucson", value: "Hyundai Tucson" },
    { label: "Hyundai Kona", value: "Hyundai Kona" },
    { label: "Hyundai Kona Electric", value: "Hyundai Kona Electric" },
    { label: "Hyundai Santa Fe", value: "Hyundai Santa Fe" },
    { label: "Hyundai Palisade", value: "Hyundai Palisade" },
    { label: "Hyundai Sonata", value: "Hyundai Sonata" },
    { label: "Hyundai Elantra", value: "Hyundai Elantra" },
    { label: "Hyundai Genesis", value: "Hyundai Genesis" },
    { label: "Hyundai Azera", value: "Hyundai Azera" },
    { label: "Hyundai Veloster", value: "Hyundai Veloster" },
    { label: "Hyundai Coupe", value: "Hyundai Coupe" },
    { label: "Hyundai Starex", value: "Hyundai Starex" },
    { label: "Hyundai H-1", value: "Hyundai H-1" },
    { label: "Hyundai H350", value: "Hyundai H350" },
    { label: "Hyundai Nexo", value: "Hyundai Nexo" },
    { label: "Hyundai Bayon", value: "Hyundai Bayon" },
    { label: "Hyundai Extera", value: "Hyundai Extera" },
    { label: "Hyundai Terracan", value: "Hyundai Terracan" },
    { label: "Hyundai Creta", value: "Hyundai Creta" },
    { label: "Hyundai H350", value: "Hyundai H350" },
    { label: "Hyundai Eon", value: "Hyundai Eon" },
    { label: "Hyundai Matrix", value: "Hyundai Matrix" },
  ],

  Infiniti: [
    { label: "Infiniti EX", value: "Infiniti EX" },
    { label: "Infiniti FX", value: "Infiniti FX" },
    { label: "Infiniti G", value: "Infiniti G" },
    { label: "Infiniti M", value: "Infiniti M" },
    { label: "Infiniti Q50", value: "Infiniti Q50" },
    { label: "Infiniti Q60", value: "Infiniti Q60" },
    { label: "Infiniti Q70", value: "Infiniti Q70" },
    { label: "Infiniti QX50", value: "Infiniti QX50" },
    { label: "Infiniti QX60", value: "Infiniti QX60" },
    { label: "Infiniti QX80", value: "Infiniti QX80" },
    { label: "Jaguar E-Pace", value: "Jaguar E-Pace" },
    { label: "Jaguar F-Pace", value: "Jaguar F-Pace" },
    { label: "Jaguar F-Type", value: "Jaguar F-Type" },
    { label: "Jaguar I-Pace", value: "Jaguar I-Pace" },
    { label: "Jaguar XE", value: "Jaguar XE" },
    { label: "Jaguar XF", value: "Jaguar XF" },
    { label: "Jaguar XJ", value: "Jaguar XJ" },
    { label: "Jaguar XK", value: "Jaguar XK" },
  ],

  Jaguar: [
    { label: "Jaguar E-Pace", value: "Jaguar E-Pace" },
    { label: "Jaguar F-Pace", value: "Jaguar F-Pace" },
    { label: "Jaguar F-Type", value: "Jaguar F-Type" },
    { label: "Jaguar I-Pace", value: "Jaguar I-Pace" },
    { label: "Jaguar XE", value: "Jaguar XE" },
    { label: "Jaguar XF", value: "Jaguar XF" },
    { label: "Jaguar XJ", value: "Jaguar XJ" },
    { label: "Jaguar XK", value: "Jaguar XK" },
  ],

  Jeep: [
    { label: "Jeep Wrangler", value: "Jeep Wrangler" },
    { label: "Jeep Grand Cherokee", value: "Jeep Grand Cherokee" },
    { label: "Jeep Cherokee", value: "Jeep Cherokee" },
    { label: "Jeep Compass", value: "Jeep Compass" },
    { label: "Jeep Renegade", value: "Jeep Renegade" },
    { label: "Jeep Gladiator", value: "Jeep Gladiator" },
    { label: "Jeep Wagoneer", value: "Jeep Wagoneer" },
    { label: "Jeep Grand Wagoneer", value: "Jeep Grand Wagoneer" },
    { label: "Jeep Liberty", value: "Jeep Liberty" },
    { label: "Jeep Patriot", value: "Jeep Patriot" },
    { label: "Jeep Commander", value: "Jeep Commander" },
    { label: "Jeep CJ", value: "Jeep CJ" },
    { label: "Jeep CJ-5", value: "Jeep CJ-5" },
    { label: "Jeep CJ-7", value: "Jeep CJ-7" },
    { label: "Jeep CJ-8 Scrambler", value: "Jeep CJ-8 Scrambler" },
    { label: "Jeep Wagoneer (1963-1991)", value: "Jeep Wagoneer (1963-1991)" },
    { label: "Jeep Gladiator (1962-1988)", value: "Jeep Gladiator (1962-1988)" },
  ],

  Kia: [
    { label: "Kia Picanto", value: "Kia Picanto" },
    { label: "Kia Rio", value: "Kia Rio" },
    { label: "Kia Stonic", value: "Kia Stonic" },
    { label: "Kia Ceed", value: "Kia Ceed" },
    { label: "Kia Ceed Sportswagon", value: "Kia Ceed Sportswagon" },
    { label: "Kia ProCeed", value: "Kia ProCeed" },
    { label: "Kia Optima", value: "Kia Optima" },
    { label: "Kia K5", value: "Kia K5" },
    { label: "Kia Sorento", value: "Kia Sorento" },
    { label: "Kia Sportage", value: "Kia Sportage" },
    { label: "Kia Niro", value: "Kia Niro" },
    { label: "Kia Niro EV", value: "Kia Niro EV" },
    { label: "Kia Soul", value: "Kia Soul" },
    { label: "Kia Stinger", value: "Kia Stinger" },
    { label: "Kia Carnival", value: "Kia Carnival" },
    { label: "Kia Sedona", value: "Kia Sedona" },
    { label: "Kia Cadenza", value: "Kia Cadenza" },
    { label: "Kia Forte", value: "Kia Forte" },
    { label: "Kia Mohave", value: "Kia Mohave" },
    { label: "Kia K900", value: "Kia K900" },
    { label: "Kia Ray", value: "Kia Ray" },
    { label: "Kia Xceed", value: "Kia Xceed" },
    { label: "Kia Seltos", value: "Kia Seltos" },
    { label: "Kia E-Niro", value: "Kia E-Niro" },
    { label: "Kia Soul EV", value: "Kia Soul EV" },
  ],

  Lamborghini: [
    { label: "Lamborghini Aventador", value: "Lamborghini Aventador" },
    { label: "Lamborghini Gallardo", value: "Lamborghini Gallardo" },
    { label: "Lamborghini Huracan", value: "Lamborghini Huracan" },
    { label: "Lamborghini Urus", value: "Lamborghini Urus" },
    { label: "Land Rover Defender", value: "Land Rover Defender" },
    { label: "Land Rover Discovery", value: "Land Rover Discovery" },
    { label: "Land Rover Discovery Sport", value: "Land Rover Discovery Sport" },
    { label: "Land Rover Range Rover", value: "Land Rover Range Rover" },
    { label: "Land Rover Range Rover Evoque", value: "Land Rover Range Rover Evoque" },
    { label: "Land Rover Range Rover Sport", value: "Land Rover Range Rover Sport" },
    { label: "Land Rover Range Rover Velar", value: "Land Rover Range Rover Velar" },
    { label: "Lexus CT", value: "Lexus CT" },
    { label: "Lexus ES", value: "Lexus ES" },
    { label: "Lexus GS", value: "Lexus GS" },
    { label: "Lexus GX", value: "Lexus GX" },
    { label: "Lexus IS", value: "Lexus IS" },
    { label: "Lexus LC", value: "Lexus LC" },
    { label: "Lexus LS", value: "Lexus LS" },
    { label: "Lexus LX", value: "Lexus LX" },
    { label: "Lexus NX", value: "Lexus NX" },
    { label: "Lexus RC", value: "Lexus RC" },
    { label: "Lexus RX", value: "Lexus RX" },
    { label: "Lexus SC", value: "Lexus SC" },
    { label: "Lexus UX", value: "Lexus UX" },
  ],

  "Land Rover": [
    { label: "Land Rover Defender", value: "Land Rover Defender" },
    { label: "Land Rover Discovery", value: "Land Rover Discovery" },
    { label: "Land Rover Discovery Sport", value: "Land Rover Discovery Sport" },
    { label: "Land Rover Range Rover", value: "Land Rover Range Rover" },
    { label: "Land Rover Range Rover Evoque", value: "Land Rover Range Rover Evoque" },
    { label: "Land Rover Range Rover Sport", value: "Land Rover Range Rover Sport" },
    { label: "Land Rover Range Rover Velar", value: "Land Rover Range Rover Velar" },
  ],

  Lincoln: [
    { label: "Lincoln Aviator", value: "Lincoln Aviator" },
    { label: "Lincoln Continental", value: "Lincoln Continental" },
    { label: "Lincoln Corsair", value: "Lincoln Corsair" },
    { label: "Lincoln MKT", value: "Lincoln MKT" },
    { label: "Lincoln MKX", value: "Lincoln MKX" },
    { label: "Lincoln MKZ", value: "Lincoln MKZ" },
    { label: "Lincoln Nautilus", value: "Lincoln Nautilus" },
    { label: "Lincoln Navigator", value: "Lincoln Navigator" },
    { label: "Lincoln Zephyr", value: "Lincoln Zephyr" },
  ],

  Lexus: [
    { label: "Lexus CT", value: "Lexus CT" },
    { label: "Lexus ES", value: "Lexus ES" },
    { label: "Lexus GS", value: "Lexus GS" },
    { label: "Lexus GX", value: "Lexus GX" },
    { label: "Lexus IS", value: "Lexus IS" },
    { label: "Lexus LC", value: "Lexus LC" },
    { label: "Lexus LS", value: "Lexus LS" },
    { label: "Lexus LX", value: "Lexus LX" },
    { label: "Lexus NX", value: "Lexus NX" },
    { label: "Lexus RC", value: "Lexus RC" },
    { label: "Lexus RX", value: "Lexus RX" },
    { label: "Lexus SC", value: "Lexus SC" },
    { label: "Lexus UX", value: "Lexus UX" },
  ],

  Maserati: [
    { label: "Maserati Ghibli", value: "Maserati Ghibli" },
    { label: "Maserati GranTurismo", value: "Maserati GranTurismo" },
    { label: "Maserati Levante", value: "Maserati Levante" },
    { label: "Maserati Quattroporte", value: "Maserati Quattroporte" },
  ],

  Mazda: [
    { label: "Mazda2", value: "Mazda2" },
    { label: "Mazda3", value: "Mazda3" },
    { label: "Mazda3 Hatchback", value: "Mazda3 Hatchback" },
    { label: "Mazda3 Sedan", value: "Mazda3 Sedan" },
    { label: "Mazda6", value: "Mazda6" },
    { label: "Mazda CX-3", value: "Mazda CX-3" },
    { label: "Mazda CX-30", value: "Mazda CX-30" },
    { label: "Mazda CX-5", value: "Mazda CX-5" },
    { label: "Mazda CX-50", value: "Mazda CX-50" },
    { label: "Mazda CX-7", value: "Mazda CX-7" },
    { label: "Mazda CX-9", value: "Mazda CX-9" },
    { label: "Mazda MX-5 Miata", value: "Mazda MX-5 Miata" },
    { label: "Mazda MX-5 RF", value: "Mazda MX-5 RF" },
    { label: "Mazda MX-30", value: "Mazda MX-30" },
    { label: "Mazda Tribute", value: "Mazda Tribute" },
    { label: "Mazda RX-7", value: "Mazda RX-7" },
    { label: "Mazda RX-8", value: "Mazda RX-8" },
    { label: "Mazda MX-5", value: "Mazda MX-5" },
    { label: "Mazda MPV", value: "Mazda MPV" },
    { label: "Mazda B-Series", value: "Mazda B-Series" },
    { label: "Mazda 2", value: "Mazda 2" },
    { label: "Mazda 3", value: "Mazda 3" },
    { label: "Mazda 6", value: "Mazda 6" },
    { label: "Mazda 626", value: "Mazda 626" },
    { label: "Mazda 929", value: "Mazda 929" },
    { label: "Mazda MX-6", value: "Mazda MX-6" },
    { label: "Mazda 3", value: "Mazda 3" },
    { label: "Mazda 5", value: "Mazda 5" },
    { label: "Mazda 323", value: "Mazda 323" },
  ],

  McLaren: [
    { label: "McLaren 570S", value: "McLaren 570S" },
    { label: "McLaren 650S", value: "McLaren 650S" },
    { label: "McLaren 675LT", value: "McLaren 675LT" },
    { label: "McLaren 720S", value: "McLaren 720S" },
    { label: "McLaren GT", value: "McLaren GT" },
    { label: "McLaren P1", value: "McLaren P1" },
  ],

  Mercedes: [
    { label: "Mercedes-Benz A-Class", value: "Mercedes-Benz A-Class" },
    { label: "Mercedes-Benz A-Class Sedan", value: "Mercedes-Benz A-Class Sedan" },
    { label: "Mercedes-Benz A-Class Hatchback", value: "Mercedes-Benz A-Class Hatchback" },
    { label: "Mercedes-Benz B-Class", value: "Mercedes-Benz B-Class" },
    { label: "Mercedes-Benz C-Class", value: "Mercedes-Benz C-Class" },
    { label: "Mercedes-Benz C-Class Sedan", value: "Mercedes-Benz C-Class Sedan" },
    { label: "Mercedes-Benz C-Class Coupe", value: "Mercedes-Benz C-Class Coupe" },
    { label: "Mercedes-Benz C-Class Cabriolet", value: "Mercedes-Benz C-Class Cabriolet" },
    { label: "Mercedes-Benz CLA-Class", value: "Mercedes-Benz CLA-Class" },
    { label: "Mercedes-Benz CLA-Class Coupe", value: "Mercedes-Benz CLA-Class Coupe" },
    {
      label: "Mercedes-Benz CLA-Class Shooting Brake",
      value: "Mercedes-Benz CLA-Class Shooting Brake",
    },
    { label: "Mercedes-Benz CLS-Class", value: "Mercedes-Benz CLS-Class" },
    { label: "Mercedes-Benz CLS-Class Coupe", value: "Mercedes-Benz CLS-Class Coupe" },
    { label: "Mercedes-Benz E-Class", value: "Mercedes-Benz E-Class" },
    { label: "Mercedes-Benz E-Class Sedan", value: "Mercedes-Benz E-Class Sedan" },
    { label: "Mercedes-Benz E-Class Coupe", value: "Mercedes-Benz E-Class Coupe" },
    { label: "Mercedes-Benz E-Class Cabriolet", value: "Mercedes-Benz E-Class Cabriolet" },
    { label: "Mercedes-Benz E-Class All-Terrain", value: "Mercedes-Benz E-Class All-Terrain" },
    { label: "Mercedes-Benz S-Class", value: "Mercedes-Benz S-Class" },
    { label: "Mercedes-Benz S-Class Sedan", value: "Mercedes-Benz S-Class Sedan" },
    { label: "Mercedes-Benz S-Class Coupe", value: "Mercedes-Benz S-Class Coupe" },
    { label: "Mercedes-Benz S-Class Cabriolet", value: "Mercedes-Benz S-Class Cabriolet" },
    { label: "Mercedes-Benz GLA-Class", value: "Mercedes-Benz GLA-Class" },
    { label: "Mercedes-Benz GLA-Class SUV", value: "Mercedes-Benz GLA-Class SUV" },
    { label: "Mercedes-Benz GLB-Class", value: "Mercedes-Benz GLB-Class" },
    { label: "Mercedes-Benz GLB-Class SUV", value: "Mercedes-Benz GLB-Class SUV" },
    { label: "Mercedes-Benz GLC-Class", value: "Mercedes-Benz GLC-Class" },
    { label: "Mercedes-Benz GLC-Class SUV", value: "Mercedes-Benz GLC-Class SUV" },
    { label: "Mercedes-Benz GLC-Class Coupe", value: "Mercedes-Benz GLC-Class Coupe" },
    { label: "Mercedes-Benz GLE-Class", value: "Mercedes-Benz GLE-Class" },
    { label: "Mercedes-Benz GLE-Class SUV", value: "Mercedes-Benz GLE-Class SUV" },
    { label: "Mercedes-Benz GLE-Class Coupe", value: "Mercedes-Benz GLE-Class Coupe" },
    { label: "Mercedes-Benz GLS-Class", value: "Mercedes-Benz GLS-Class" },
    { label: "Mercedes-Benz GLS-Class SUV", value: "Mercedes-Benz GLS-Class SUV" },
    { label: "Mercedes-Benz G-Class", value: "Mercedes-Benz G-Class" },
    { label: "Mercedes-Benz G-Class SUV", value: "Mercedes-Benz G-Class SUV" },
    { label: "Mercedes-Benz EQB", value: "Mercedes-Benz EQB" },
    { label: "Mercedes-Benz EQC", value: "Mercedes-Benz EQC" },
    { label: "Mercedes-Benz EQS", value: "Mercedes-Benz EQS" },
    { label: "Mercedes-Benz EQS SUV", value: "Mercedes-Benz EQS SUV" },
    { label: "Mercedes-Benz SLS AMG", value: "Mercedes-Benz SLS AMG" },
    { label: "Mercedes-Benz AMG GT", value: "Mercedes-Benz AMG GT" },
    { label: "Mercedes-Benz AMG GT Coupe", value: "Mercedes-Benz AMG GT Coupe" },
    { label: "Mercedes-Benz AMG GT Roadster", value: "Mercedes-Benz AMG GT Roadster" },
    { label: "Mercedes-Benz CLS 63 AMG", value: "Mercedes-Benz CLS 63 AMG" },
    { label: "Mercedes-Benz C63 AMG", value: "Mercedes-Benz C63 AMG" },
    { label: "Mercedes-Benz E63 AMG", value: "Mercedes-Benz E63 AMG" },
    { label: "Mercedes-Benz G63 AMG", value: "Mercedes-Benz G63 AMG" },
    { label: "Mercedes-Benz GLE 63 AMG", value: "Mercedes-Benz GLE 63 AMG" },
  ],

  Mini: [
    { label: "Mini Cooper", value: "Mini Cooper" },
    { label: "Mini Countryman", value: "Mini Countryman" },
    { label: "Mini Paceman", value: "Mini Paceman" },
  ],

  Mitsubishi: [
    { label: "Mitsubishi Outlander", value: "Mitsubishi Outlander" },
    { label: "Mitsubishi Outlander PHEV", value: "Mitsubishi Outlander PHEV" },
    { label: "Mitsubishi ASX", value: "Mitsubishi ASX" },
    { label: "Mitsubishi Eclipse Cross", value: "Mitsubishi Eclipse Cross" },
    { label: "Mitsubishi RVR", value: "Mitsubishi RVR" },
    { label: "Mitsubishi Pajero", value: "Mitsubishi Pajero" },
    { label: "Mitsubishi Pajero Sport", value: "Mitsubishi Pajero Sport" },
    { label: "Mitsubishi Triton", value: "Mitsubishi Triton" },
    { label: "Mitsubishi L200", value: "Mitsubishi L200" },
    { label: "Mitsubishi Colt", value: "Mitsubishi Colt" },
    { label: "Mitsubishi Lancer", value: "Mitsubishi Lancer" },
    { label: "Mitsubishi Galant", value: "Mitsubishi Galant" },
    { label: "Mitsubishi Mirage", value: "Mitsubishi Mirage" },
    { label: "Mitsubishi i-MiEV", value: "Mitsubishi i-MiEV" },
    { label: "Mitsubishi Montero", value: "Mitsubishi Montero" },
    { label: "Mitsubishi Space Star", value: "Mitsubishi Space Star" },
    { label: "Mitsubishi Outlander Sport", value: "Mitsubishi Outlander Sport" },
    { label: "Mitsubishi Evolve", value: "Mitsubishi Evolve" },
    { label: "Mitsubishi Cordia", value: "Mitsubishi Cordia" },
    { label: "Mitsubishi Starion", value: "Mitsubishi Starion" },
    { label: "Mitsubishi Galant VR-4", value: "Mitsubishi Galant VR-4" },
    { label: "Mitsubishi Delica", value: "Mitsubishi Delica" },
    { label: "Mitsubishi Delica D:5", value: "Mitsubishi Delica D:5" },
    { label: "Mitsubishi Lancer Evolution", value: "Mitsubishi Lancer Evolution" },
  ],

  Neta: [
    { label: "Neta V", value: "Neta V" },
    { label: "Neta U", value: "Neta U" },
    { label: "Neta S", value: "Neta S" },
    { label: "Neta X", value: "Neta X" },
  ],

  Nissan: [
    { label: "Nissan Altima", value: "Nissan Altima" },
    { label: "Nissan 370Z", value: "Nissan 370Z" },
    { label: "Nissan 350Z", value: "Nissan 350Z" },
    { label: "Nissan 240SX", value: "Nissan 240SX" },
    { label: "Nissan Maxima", value: "Nissan Maxima" },
    { label: "Nissan Sentra", value: "Nissan Sentra" },
    { label: "Nissan Versa", value: "Nissan Versa" },
    { label: "Nissan GT-R", value: "Nissan GT-R" },
    { label: "Nissan Juke", value: "Nissan Juke" },
    { label: "Nissan Rogue", value: "Nissan Rogue" },
    { label: "Nissan Rogue Sport", value: "Nissan Rogue Sport" },
    { label: "Nissan Murano", value: "Nissan Murano" },
    { label: "Nissan Pathfinder", value: "Nissan Pathfinder" },
    { label: "Nissan Armada", value: "Nissan Armada" },
    { label: "Nissan Xterra", value: "Nissan Xterra" },
    { label: "Nissan Frontier", value: "Nissan Frontier" },
    { label: "Nissan Titan", value: "Nissan Titan" },
    { label: "Nissan Titan XD", value: "Nissan Titan XD" },
    { label: "Nissan NV200", value: "Nissan NV200" },
    { label: "Nissan NV3500", value: "Nissan NV3500" },
    { label: "Nissan Leaf", value: "Nissan Leaf" },
    { label: "Nissan Kicks", value: "Nissan Kicks" },
    { label: "Nissan Juke", value: "Nissan Juke" },
    { label: "Nissan Silvia", value: "Nissan Silvia" },
    { label: "Nissan 370Z Roadster", value: "Nissan 370Z Roadster" },
    { label: "Nissan GT-R Nismo", value: "Nissan GT-R Nismo" },
    { label: "Nissan GT-R Premium", value: "Nissan GT-R Premium" },
    { label: "Nissan GT-R Track Edition", value: "Nissan GT-R Track Edition" },
    { label: "Nissan GT-R 50th Anniversary", value: "Nissan GT-R 50th Anniversary" },
  ],

  Pagani: [
    { label: "Pagani Huayra", value: "Pagani Huayra" },
    { label: "Pagani Zonda", value: "Pagani Zonda" },
  ],

  Peugeot: [
    { label: "Peugeot 108", value: "Peugeot 108" },
    { label: "Peugeot 2008", value: "Peugeot 2008" },
    { label: "Peugeot 208", value: "Peugeot 208" },
    { label: "Peugeot 3008", value: "Peugeot 3008" },
    { label: "Peugeot 308", value: "Peugeot 308" },
    { label: "Peugeot 308 SW", value: "Peugeot 308 SW" },
    { label: "Peugeot 5008", value: "Peugeot 5008" },
    { label: "Peugeot 508", value: "Peugeot 508" },
    { label: "Peugeot 508 SW", value: "Peugeot 508 SW" },
    { label: "Peugeot 807", value: "Peugeot 807" },
    { label: "Peugeot 908", value: "Peugeot 908" },
    { label: "Peugeot Partner", value: "Peugeot Partner" },
    { label: "Peugeot Rifter", value: "Peugeot Rifter" },
    { label: "Peugeot Expert", value: "Peugeot Expert" },
    { label: "Peugeot Traveller", value: "Peugeot Traveller" },
    { label: "Peugeot 404", value: "Peugeot 404" },
    { label: "Peugeot 504", value: "Peugeot 504" },
    { label: "Peugeot 205", value: "Peugeot 205" },
    { label: "Peugeot 206", value: "Peugeot 206" },
    { label: "Peugeot 207", value: "Peugeot 207" },
    { label: "Peugeot 208 GTi", value: "Peugeot 208 GTi" },
    { label: "Peugeot 308 GTi", value: "Peugeot 308 GTi" },
    { label: "Peugeot 406", value: "Peugeot 406" },
    { label: "Peugeot 407", value: "Peugeot 407" },
    { label: "Peugeot 508 PSE", value: "Peugeot 508 PSE" },
    { label: "Peugeot e-208", value: "Peugeot e-208" },
    { label: "Peugeot e-2008", value: "Peugeot e-2008" },
    { label: "Peugeot e-Partner", value: "Peugeot e-Partner" },
    { label: "Peugeot e-Expert", value: "Peugeot e-Expert" },
    { label: "Peugeot e-Traveller", value: "Peugeot e-Traveller" },
  ],

  Pontiac: [
    { label: "Pontiac Aztek", value: "Pontiac Aztek" },
    { label: "Pontiac Bonneville", value: "Pontiac Bonneville" },
    { label: "Pontiac Firebird", value: "Pontiac Firebird" },
    { label: "Pontiac G5", value: "Pontiac G5" },
    { label: "Pontiac G6", value: "Pontiac G6" },
    { label: "Pontiac G8", value: "Pontiac G8" },
    { label: "Pontiac Grand Am", value: "Pontiac Grand Am" },
    { label: "Pontiac Grand Prix", value: "Pontiac Grand Prix" },
    { label: "Pontiac GTO", value: "Pontiac GTO" },
    { label: "Pontiac Montana", value: "Pontiac Montana" },
    { label: "Pontiac Solstice", value: "Pontiac Solstice" },
    { label: "Pontiac Sunfire", value: "Pontiac Sunfire" },
  ],

  Porsche: [
    { label: "Porsche 911", value: "Porsche 911" },
    { label: "Porsche 918", value: "Porsche 918" },
    { label: "Porsche Boxster", value: "Porsche Boxster" },
    { label: "Porsche Cayenne", value: "Porsche Cayenne" },
    { label: "Porsche Cayman", value: "Porsche Cayman" },
    { label: "Porsche Macan", value: "Porsche Macan" },
    { label: "Porsche Panamera", value: "Porsche Panamera" },
  ],

  "Range Rover": [
    { label: "Range Rover", value: "Range Rover" },
    { label: "Range Rover Classic", value: "Range Rover Classic" },
    { label: "Range Rover P38", value: "Range Rover P38" },
    { label: "Range Rover L322", value: "Range Rover L322" },
    { label: "Range Rover L405", value: "Range Rover L405" },
    { label: "Range Rover L460", value: "Range Rover L460" },
    { label: "Range Rover Sport", value: "Range Rover Sport" },
    { label: "Range Rover Sport L320", value: "Range Rover Sport L320" },
    { label: "Range Rover Sport L494", value: "Range Rover Sport L494" },
    { label: "Range Rover Sport L663", value: "Range Rover Sport L663" },
    { label: "Range Rover Evoque", value: "Range Rover Evoque" },
    { label: "Range Rover Evoque L538", value: "Range Rover Evoque L538" },
    { label: "Range Rover Evoque L551", value: "Range Rover Evoque L551" },
    { label: "Range Rover Velar", value: "Range Rover Velar" },
    { label: "Range Rover Velar L560", value: "Range Rover Velar L560" },
    { label: "Range Rover Velar L610", value: "Range Rover Velar L610" },
    { label: "Range Rover SVAutobiography", value: "Range Rover SVAutobiography" },
    { label: "Range Rover Autobiography", value: "Range Rover Autobiography" },
  ],

  Ram: [
    { label: "Ram 1500", value: "Ram 1500" },
    { label: "Ram 2500", value: "Ram 2500" },
    { label: "Ram 3500", value: "Ram 3500" },
  ],

  Renault: [
    { label: "Renault Clio", value: "Renault Clio" },
    { label: "Renault Clio IV", value: "Renault Clio IV" },
    { label: "Renault Clio V", value: "Renault Clio V" },
    { label: "Renault Captur", value: "Renault Captur" },
    { label: "Renault Captur E-Tech", value: "Renault Captur E-Tech" },
    { label: "Renault Megane", value: "Renault Megane" },
    { label: "Renault Megane III", value: "Renault Megane III" },
    { label: "Renault Megane IV", value: "Renault Megane IV" },
    { label: "Renault Megane V", value: "Renault Megane V" },
    { label: "Renault Megane E-Tech", value: "Renault Megane E-Tech" },
    { label: "Renault Koleos", value: "Renault Koleos" },
    { label: "Renault Kadjar", value: "Renault Kadjar" },
    { label: "Renault Talisman", value: "Renault Talisman" },
    { label: "Renault Talisman Estate", value: "Renault Talisman Estate" },
    { label: "Renault Espace", value: "Renault Espace" },
    { label: "Renault Scenic", value: "Renault Scenic" },
    { label: "Renault Grand Scenic", value: "Renault Grand Scenic" },
    { label: "Renault Zoe", value: "Renault Zoe" },
    { label: "Renault Zoe E-Tech", value: "Renault Zoe E-Tech" },
    { label: "Renault Kangoo", value: "Renault Kangoo" },
    { label: "Renault Kangoo Z.E.", value: "Renault Kangoo Z.E." },
    { label: "Renault Trafic", value: "Renault Trafic" },
    { label: "Renault Master", value: "Renault Master" },
    { label: "Renault Twizy", value: "Renault Twizy" },
    { label: "Renault Alpine A110", value: "Renault Alpine A110" },
    { label: "Renault Laguna", value: "Renault Laguna" },
    { label: "Renault Laguna II", value: "Renault Laguna II" },
    { label: "Renault Laguna III", value: "Renault Laguna III" },
    { label: "Renault Wind", value: "Renault Wind" },
    { label: "Renault Fluence", value: "Renault Fluence" },
    { label: "Renault Avantime", value: "Renault Avantime" },
    { label: "Renault Fuego", value: "Renault Fuego" },
    { label: "Renault 4", value: "Renault 4" },
    { label: "Renault 5", value: "Renault 5" },
    { label: "Renault 6", value: "Renault 6" },
    { label: "Renault 7", value: "Renault 7" },
    { label: "Renault 8", value: "Renault 8" },
    { label: "Renault 9", value: "Renault 9" },
    { label: "Renault 11", value: "Renault 11" },
    { label: "Renault 12", value: "Renault 12" },
  ],

  "Rolls-Royce": [
    { label: "Rolls-Royce Cullinan", value: "Rolls-Royce Cullinan" },
    { label: "Rolls-Royce Dawn", value: "Rolls-Royce Dawn" },
    { label: "Rolls-Royce Ghost", value: "Rolls-Royce Ghost" },
    { label: "Rolls-Royce Phantom", value: "Rolls-Royce Phantom" },
    { label: "Rolls-Royce Wraith", value: "Rolls-Royce Wraith" },
  ],

  Saab: [
    { label: "Saab 9-3", value: "Saab 9-3" },
    { label: "Saab 9-5", value: "Saab 9-5" },
    { label: "Saab 900", value: "Saab 900" },
    { label: "Saab 9000", value: "Saab 9000" },
  ],

  Saturn: [
    { label: "Saturn Aura", value: "Saturn Aura" },
    { label: "Saturn Ion", value: "Saturn Ion" },
    { label: "Saturn L-Series", value: "Saturn L-Series" },
    { label: "Saturn Outlook", value: "Saturn Outlook" },
    { label: "Saturn Relay", value: "Saturn Relay" },
    { label: "Saturn Sky", value: "Saturn Sky" },
    { label: "Saturn VUE", value: "Saturn VUE" },
    { label: "Scion FR-S", value: "Scion FR-S" },
  ],

  Scion: [
    { label: "Scion iM", value: "Scion iM" },
    { label: "Scion iQ", value: "Scion iQ" },
    { label: "Scion tC", value: "Scion tC" },
    { label: "Scion xA", value: "Scion xA" },
    { label: "Scion xB", value: "Scion xB" },
    { label: "Scion xD", value: "Scion xD" },
  ],

  Smart: [{ label: "Smart Fortwo", value: "Smart Fortwo" }],

  Spyker: [
    { label: "Spyker C8", value: "Spyker C8" },
    { label: "Spyker C8 Laviolette", value: "Spyker C8 Laviolette" },
    { label: "Spyker C8 Spyder", value: "Spyker C8 Spyder" },
    { label: "Spyker C8 Spyder T", value: "Spyker C8 Spyder T" },
    { label: "Spyker C8 Aileron", value: "Spyker C8 Aileron" },
  ],

  Subaru: [
    { label: "Subaru Ascent", value: "Subaru Ascent" },
    { label: "Subaru BRZ", value: "Subaru BRZ" },
    { label: "Subaru Crosstrek", value: "Subaru Crosstrek" },
    { label: "Subaru Forester", value: "Subaru Forester" },
    { label: "Subaru Impreza", value: "Subaru Impreza" },
    { label: "Subaru Legacy", value: "Subaru Legacy" },
    { label: "Subaru Outback", value: "Subaru Outback" },
    { label: "Subaru WRX", value: "Subaru WRX" },
  ],

  Suzuki: [
    { label: "Suzuki Alto", value: "Suzuki Alto" },
    { label: "Suzuki Alto Works", value: "Suzuki Alto Works" },
    { label: "Suzuki Alto Lapin", value: "Suzuki Alto Lapin" },
    { label: "Suzuki Baleno", value: "Suzuki Baleno" },
    { label: "Suzuki Celerio", value: "Suzuki Celerio" },
    { label: "Suzuki Dzire", value: "Suzuki Dzire" },
    { label: "Suzuki Ignis", value: "Suzuki Ignis" },
    { label: "Suzuki Jimny", value: "Suzuki Jimny" },
    { label: "Suzuki Swift", value: "Suzuki Swift" },
    { label: "Suzuki Wagon R", value: "Suzuki Wagon R" },
    { label: "Suzuki Aerio", value: "Suzuki Aerio" },
    { label: "Suzuki Forenza", value: "Suzuki Forenza" },
    { label: "Suzuki Grand Vitara", value: "Suzuki Grand Vitara" },
    { label: "Suzuki Kizashi", value: "Suzuki Kizashi" },
    { label: "Suzuki Kizashi Sport", value: "Suzuki Kizashi Sport" },
    { label: "Suzuki SX4", value: "Suzuki SX4" },
    { label: "Suzuki SX4 S-Cross", value: "Suzuki SX4 S-Cross" },
    { label: "Suzuki Vitara", value: "Suzuki Vitara" },
    { label: "Suzuki Vitara XL7", value: "Suzuki Vitara XL7" },
    { label: "Suzuki XL7", value: "Suzuki XL7" },
    { label: "Suzuki Alto 660", value: "Suzuki Alto 660" },
    { label: "Suzuki Capuccino", value: "Suzuki Capuccino" },
    { label: "Suzuki Carry", value: "Suzuki Carry" },
    { label: "Suzuki Grand Escudo", value: "Suzuki Grand Escudo" },
    { label: "Suzuki Liana", value: "Suzuki Liana" },
    { label: "Suzuki Sidekick", value: "Suzuki Sidekick" },
    { label: "Suzuki Swift DZire", value: "Suzuki Swift DZire" },
    { label: "Suzuki S-Cross", value: "Suzuki S-Cross" },
    { label: "Suzuki Jimny Sierra", value: "Suzuki Jimny Sierra" },
    { label: "Suzuki Alto Turbo RS", value: "Suzuki Alto Turbo RS" },
    { label: "Suzuki Escudo", value: "Suzuki Escudo" },
    { label: "Suzuki X-90", value: "Suzuki X-90" },
  ],

  Tesla: [
    { label: "Tesla Model S", value: "Tesla Model S" },
    { label: "Tesla Model S Plaid", value: "Tesla Model S Plaid" },
    { label: "Tesla Model 3", value: "Tesla Model 3" },
    { label: "Tesla Model 3 Performance", value: "Tesla Model 3 Performance" },
    { label: "Tesla Model X", value: "Tesla Model X" },
    { label: "Tesla Model X Plaid", value: "Tesla Model X Plaid" },
    { label: "Tesla Model Y", value: "Tesla Model Y" },
    { label: "Tesla Model Y Performance", value: "Tesla Model Y Performance" },
    { label: "Tesla Cybertruck", value: "Tesla Cybertruck" },
    { label: "Tesla Roadster", value: "Tesla Roadster" },
    { label: "Tesla Semi", value: "Tesla Semi" },
  ],

  Toyota: [
    { label: "Toyota Aygo", value: "Toyota Aygo" },
    { label: "Toyota Yaris", value: "Toyota Yaris" },
    { label: "Toyota Yaris Cross", value: "Toyota Yaris Cross" },
    { label: "Toyota Corolla", value: "Toyota Corolla" },
    { label: "Toyota Corolla Hatchback", value: "Toyota Corolla Hatchback" },
    { label: "Toyota Corolla Touring Sports", value: "Toyota Corolla Touring Sports" },
    { label: "Toyota Camry", value: "Toyota Camry" },
    { label: "Toyota Avalon", value: "Toyota Avalon" },
    { label: "Toyota Prius", value: "Toyota Prius" },
    { label: "Toyota Prius Prime", value: "Toyota Prius Prime" },
    { label: "Toyota RAV4", value: "Toyota RAV4" },
    { label: "Toyota RAV4 Hybrid", value: "Toyota RAV4 Hybrid" },
    { label: "Toyota RAV4 Prime", value: "Toyota RAV4 Prime" },
    { label: "Toyota C-HR", value: "Toyota C-HR" },
    { label: "Toyota Highlander", value: "Toyota Highlander" },
    { label: "Toyota Highlander Hybrid", value: "Toyota Highlander Hybrid" },
    { label: "Toyota 4Runner", value: "Toyota 4Runner" },
    { label: "Toyota Sequoia", value: "Toyota Sequoia" },
    { label: "Toyota Land Cruiser", value: "Toyota Land Cruiser" },
    { label: "Toyota Venza", value: "Toyota Venza" },
    { label: "Toyota Sienna", value: "Toyota Sienna" },
    { label: "Toyota Tacoma", value: "Toyota Tacoma" },
    { label: "Toyota Tundra", value: "Toyota Tundra" },
    { label: "Toyota Supra", value: "Toyota Supra" },
    { label: "Toyota 86", value: "Toyota 86" },
    { label: "Toyota GT86", value: "Toyota GT86" },
    { label: "Toyota Hilux", value: "Toyota Hilux" },
    { label: "Toyota Land Cruiser Prado", value: "Toyota Land Cruiser Prado" },
    { label: "Toyota FJ Cruiser", value: "Toyota FJ Cruiser" },
    { label: "Toyota Matrix", value: "Toyota Matrix" },
    { label: "Toyota RAV4 EV", value: "Toyota RAV4 EV" },
    { label: "Toyota Urban Cruiser", value: "Toyota Urban Cruiser" },
    { label: "Toyota Corona", value: "Toyota Corona" },
    { label: "Toyota Celica", value: "Toyota Celica" },
    { label: "Toyota Starlet", value: "Toyota Starlet" },
    { label: "Toyota Paseo", value: "Toyota Paseo" },
  ],

  Volkswagen: [
    { label: "Volkswagen Up!", value: "Volkswagen Up!" },
    { label: "Volkswagen Polo", value: "Volkswagen Polo" },
    { label: "Volkswagen Golf", value: "Volkswagen Golf" },
    { label: "Volkswagen Golf GTI", value: "Volkswagen Golf GTI" },
    { label: "Volkswagen Golf R", value: "Volkswagen Golf R" },
    { label: "Volkswagen Golf Variant", value: "Volkswagen Golf Variant" },
    { label: "Volkswagen Jetta", value: "Volkswagen Jetta" },
    { label: "Volkswagen Passat", value: "Volkswagen Passat" },
    { label: "Volkswagen Passat Variant", value: "Volkswagen Passat Variant" },
    { label: "Volkswagen Arteon", value: "Volkswagen Arteon" },
    { label: "Volkswagen Tiguan", value: "Volkswagen Tiguan" },
    { label: "Volkswagen Tiguan Allspace", value: "Volkswagen Tiguan Allspace" },
    { label: "Volkswagen Touareg", value: "Volkswagen Touareg" },
    { label: "Volkswagen Atlas", value: "Volkswagen Atlas" },
    { label: "Volkswagen ID.3", value: "Volkswagen ID.3" },
    { label: "Volkswagen ID.4", value: "Volkswagen ID.4" },
    { label: "Volkswagen ID.5", value: "Volkswagen ID.5" },
    { label: "Volkswagen ID. Buzz", value: "Volkswagen ID. Buzz" },
    { label: "Volkswagen e-Golf", value: "Volkswagen e-Golf" },
    { label: "Volkswagen Jetta GLI", value: "Volkswagen Jetta GLI" },
    { label: "Volkswagen Scirocco", value: "Volkswagen Scirocco" },
    { label: "Volkswagen Corrado", value: "Volkswagen Corrado" },
    { label: "Volkswagen Beetle", value: "Volkswagen Beetle" },
    { label: "Volkswagen Beetle Cabriolet", value: "Volkswagen Beetle Cabriolet" },
    { label: "Volkswagen Golf Plus", value: "Volkswagen Golf Plus" },
    { label: "Volkswagen Golf Sportsvan", value: "Volkswagen Golf Sportsvan" },
    { label: "Volkswagen Phaeton", value: "Volkswagen Phaeton" },
    { label: "Volkswagen Vento", value: "Volkswagen Vento" },
    { label: "Volkswagen Polo GTI", value: "Volkswagen Polo GTI" },
    { label: "Volkswagen Caddy", value: "Volkswagen Caddy" },
    { label: "Volkswagen Caddy Maxi", value: "Volkswagen Caddy Maxi" },
    { label: "Volkswagen Transporter", value: "Volkswagen Transporter" },
    { label: "Volkswagen Caravelle", value: "Volkswagen Caravelle" },
    { label: "Volkswagen California", value: "Volkswagen California" },
  ],

  Volvo: [
    { label: "Volvo C30", value: "Volvo C30" },
    { label: "Volvo C70", value: "Volvo C70" },
    { label: "Volvo S40", value: "Volvo S40" },
    { label: "Volvo S60", value: "Volvo S60" },
    { label: "Volvo S70", value: "Volvo S70" },
    { label: "Volvo S80", value: "Volvo S80" },
    { label: "Volvo S90", value: "Volvo S90" },
    { label: "Volvo V50", value: "Volvo V50" },
    { label: "Volvo V60", value: "Volvo V60" },
    { label: "Volvo V70", value: "Volvo V70" },
    { label: "Volvo V90", value: "Volvo V90" },
    { label: "Volvo XC40", value: "Volvo XC40" },
    { label: "Volvo XC60", value: "Volvo XC60" },
    { label: "Volvo XC70", value: "Volvo XC70" },
    { label: "Volvo XC90", value: "Volvo XC90" },
  ],
};
