export const carColor = [
    { label: "Argent", value: "Argent" },
    { label: "Beige", value: "Beige" },
    { label: "Blanc", value: "Blanc" },
    { label: "Bleu", value: "Bleu" },
    { label: "Bleu clair", value: "Bleu clair" },
    { label: "Bleu marine", value: "Bleu marine" },
    { label: "Bordeaux", value: "Bordeaux" },
    { label: "Gris", value: "Gris" },
    { label: "Gris clair", value: "Gris clair" },
    { label: "Gris foncé", value: "Gris foncé" },
    { label: "Jaune", value: "Jaune" },
    { label: "Marron", value: "Marron" },
    { label: "Noir", value: "Noir" },
    { label: "Orange", value: "Orange" },
    { label: "Or", value: "Or" },
    { label: "Rose", value: "Rose" },
    { label: "Rouge", value: "Rouge" },
    { label: "Turquoise", value: "Turquoise" },
    { label: "Vert", value: "Vert" },
    { label: "Vert clair", value: "Vert clair" },
    { label: "Vert foncé", value: "Vert foncé" },
    { label: "Violet", value: "Violet" },
  ];